### PR TITLE
add links related to Mathematica & Wolfram Language

### PR DESCRIPTION
**Pull request by arnoudbuzing**
This adds a few useful links to the Mathematica section of this readme file, related to Machine Learning and Neural Networks.

### CODE REVIEW

**Comment by neomatrix369** [comment]
I'm happy to merge it as it is but you like to add the narrations you had on issue #32 that would certainly enrich the content on that page

**Comment by neomatrix369** [comment]
Fixes #34

**Comment by arnoudbuzing** [comment]
Thanks, if you can merge this as is, then I will work on more improvements later?

**Comment by neomatrix369** [comment]
Sure I'll merge it now and then await other PRs

**Pull request merged**
