### PR TITLE
Added a useful resource

### PR DESCRIPTION
**Pull request by Vaishnaviamirayada**
Have added a useful resource about the programming language from the scaler topics

### CODE REVIEW

**Comment by neomatrix369** [comment]
Thanks for creating this PR can you pls share if the website associated with these links is a commercial site?

**Comment by Vaishnaviamirayada** [comment]
Hi @neomatrix369,

Here is the website with free resources: [https://www.scaler.com/topics/hubs/](https://www.scaler.com/topics/hubs/).

Video Courses:
1.  [Java for Beginners](https://www.scaler.com/topics/course/java-beginners/)
2. [C++ for Beginners](https://www.scaler.com/topics/course/cpp-beginners/)

The courses will always remain free.

**Comment by neomatrix369** [comment]
Can you also find other categories, on the repo, to add these links to? I'll merge this PR soon, sorry for the delay.

**Comment by neomatrix369** [comment]
Thanks @Vaishnaviamirayada sorry for the delay, can you also look into this in the meanwhile: https://github.com/neomatrix369/awesome-ai-ml-dl/pull/110#issuecomment-1242563720

**Pull request merged**
