### PR TITLE
Adds new DL courses

### PR DESCRIPTION
**Pull request by oke-aditya**
- Adds new DL courses from Deep Learning.ai

- I want to add some popular YouTube channels as well do let me know where I can.

cc @neomatrix369

### CODE REVIEW

**Comment by neomatrix369** [comment]
@oke-aditya I'll merge this one, but the links you share can be placed in multiple other places as well

**Comment by neomatrix369** [comment]
Please also remember to label your PR with #hacktoberfest

**Comment by oke-aditya** [comment]
@neomatrix369 
I'm not so sure where they can be. Can you let me know where YouTube channel can be added ? 
Maybe a new md section for it

**Comment by neomatrix369** [comment]
> @neomatrix369
> I'm not so sure where they can be. Can you let me know where YouTube channel can be added ?
> Maybe a new md section for it

Search for GANs or "Generative Adversarial networks" and you will see multiple pages and then look for categories in them

Find the topic/topics for YouTube channel and add them under there, all links are treated equally ;)

**Comment by neomatrix369** [comment]
> Please also remember to label your PR with #hacktoberfest

Can you check in your Hacktoberfest dashboard if you got tagged for this PR

**Comment by oke-aditya** [comment]
> 
> 
> > Please also remember to label your PR with #hacktoberfest
> 
> Can you check in your Hacktoberfest dashboard if you got tagged for this PR

Yes

**Comment by oke-aditya** [comment]
> 
> 
> > @neomatrix369
> > I'm not so sure where they can be. Can you let me know where YouTube channel can be added ?
> > Maybe a new md section for it
> 
> Search for GANs or "Generative Adversarial networks" and you will see multiple pages and then look for categories in them
> 
> Find the topic/topics for YouTube channel and add them under there, all links are treated equally ;)

I will do it, by tomorrow.

**Pull request merged**
