### PR TITLE
Update julia-python-and-r.md

### PR DESCRIPTION
**Pull request by dA505819**
Added articles

### CODE REVIEW

**Comment by neomatrix369** [comment]
Thank you @dA505819 these two links are super cool -- do you have python equivalents?

**Comment by neomatrix369** [comment]
Thanks for the PR

**Comment by dA505819** [comment]
@neomatrix369 Not yet written mani. GeeksforGeeks already have python equivalent of these topic.

Will write a separate blog on another website in future!

**Comment by dA505819** [comment]
@neomatrix369 You're Welcome mani!

**Pull request merged**
