### PR TITLE
optimize: Optimizes All Images By 49.37%

### PR DESCRIPTION
**Pull request by PrynsTag**
I optimized all your images for you and saved 49.37% of space.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Hey Thanks for doing this @PrynsTag, can you please share some screenshots of the after-effects of this optimisation?

**Comment by neomatrix369** [comment]
One suggestion I would like to make and it will make both of our lives easier - to split this PR into smaller PRs so we can verify the changes images are the same and we haven't regressed

**Comment by PrynsTag** [comment]
Your welcome! As per your 2nd request in splitting this PR, this PR is reliant on ImgBot and is generated automatically. I have read their documentation [here](https://imgbot.net/docs/) however they are not providing such configuration. I have also looked at other PR of ImgBot to quantify what I have said:
- https://github.com/yezz123/DogeAPI/pull/3
- https://github.com/dogecoin/dogecoin/pull/1800

However the issue is the same.

Your first request is integrated in GitHub. Just go to the "Files Changed Section" shown bellow
image

And then click the document icon 
image

After that you are presented with split view (by default) on what's been deleted and what's been added.
image

**Comment by PrynsTag** [comment]
I am still fairly new to ImgBot and PR and would want to learn so if you still have any concerns don't hesitate to tell me.

**Comment by neomatrix369** [comment]
> I am still fairly new to ImgBot and PR and would want to learn so if you still have any concerns don't hesitate to tell me.

I'm fine with whatever method you use to go about further, as long as we know that the optimised images are the same and are visible like they did before the optimisation.

Could you try to go thru them and see if this is the case, and let me know, thanks for the screenshots of the others above.

**Review by PrynsTag — COMMENTED** [review]
I have viewed the 47 images and I can confirm that the PR didn't break the image and the quality of the images is not reduced.

**Comment by neomatrix369** [comment]
> I have viewed the 47 images and I can confirm that the PR didn't break the image and the quality of the images is not reduced.

Thanks @PrynsTag!

**Pull request merged**
