### PR TITLE
added measures.md #hacktoberfest

### PR DESCRIPTION
**Pull request by UmaGunturi**

### CODE REVIEW

**Review by neomatrix369 — CHANGES_REQUESTED** [review]
In general looks good, but can you move the `formulae` folder into the folder where the other two `.md` files are?

You will now also need to update the respective `.md` files as the location of these images are changed.

**Review by UmaGunturi — COMMENTED** [review]
Moved the folder and updated the links!

**Review by neomatrix369 — APPROVED** [review]
Looks good, I'll merge it now.

Good work, and nice explanations

But would you mind to please add some text (short description or summary) of what the PR contains, it will help me and others who read it later on.

**Comment by UmaGunturi** [comment]
> Looks good, I'll merge it now.
> 
> Good work, and nice explanations
> 
> But would you mind to please add some text (short description or summary) of what the PR contains, it will help me and others who read it later on.

Done! @neomatrix369

**Comment by neomatrix369** [comment]
thnx @UmaGunturi

**Pull request merged**
